name: Deploy Node.js App to Amazon Linux EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Debug SSH Configuration
        run: |
          echo "EC2 Host: ${{ secrets.EC2_HOST }}"
          ls -l ~/.ssh
          cat ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ec2-user@${{ secrets.EC2_HOST }} <<EOF
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest
          docker stop node_app || true
          docker rm node_app || true
          docker run -d -p 3000:3000 --name node_app ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest
          EOF
